name: Deploy master to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script
        run: npm run deploy:catalogue
