name: Deploy master to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # checkout current branch
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Initialise monorepo
        run: yarn install

      - name: Run deploy script
        run: npm run deploy:catalogue
